name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          lfs: true

      #- name: Install Parcel
      #  run: npm install parcel-bundler

      - name: Install Dependecies
        run: npm install

      - name: Build
        run: npm run distribution

      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: log
        run: |
          ls -l

      # - name: Deploy GitHub Pages site
      #   uses: actions/deploy-pages@v4.0.3
      #   with:
      #     # GitHub token
      #     token: ${{ secrets.GHP_TOKEN }} # default is ${{ github.token }}
      #     # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
      #     timeout: 600000 # optional, default is 600000
      #     # Maximum number of status report errors before cancelling a deployment (default: 10)
      #     error_count: 10 # optional, default is 10
      #     # Time in milliseconds between two deployment status report (default: 5 seconds)
      #     reporting_interval: 5000 # optional, default is 5000
      #     # Name of the artifact to deploy
      #     artifact_name: github-pages # optional, default is github-pages
      #     # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
      #     preview: false # optional, default is false

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GHP_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.

